spring:
  application:
    name: calendar-booking-system

  mvc:
    servlet:
      path: /api/v1

appointment:
  time-validator-strategy: fullHour
  duration-minutes: 60
  booking-strategy: pessimistic
  repository: in-memory

server:
  port: 8080